=== PabloJGA97/Pr-ctica-6-Validadors-d-XML-DTD/Practica 6. Exercici 7 i 8 XML DTD/grupalie.dtd
<!ELEMENT TecnoComponentes (Componentes, Clientes, Ordenes)>
<!ELEMENT Componentes (Placa_Base, Disco_duro, procesador, ram, refrigeracion_liquida, torres, tarjeta_grafica, tarjeta_de_sonido, ventilador_CPU)>
<!ELEMENT Placa_Base (Marca* | Modelo*)>
<!ELEMENT Marca (Modelo*)>
<!ELEMENT Modelo (Nom+)>
<!ELEMENT Disco_duro (Marca* | Modelo*)>
<!ELEMENT procesador (Marca* | Modelo*)>
<!ELEMENT ram (Marca* | Modelo*)>
<!ELEMENT refrigeracion_liquida (Marca* | Modelo*)>
<!ELEMENT torres (Marca* | Modelo*)>
<!ELEMENT tarjeta_grafica (Marca* | Modelo*)>
<!ELEMENT tarjeta_de_sonido (Marca* | Modelo*)>
<!ELEMENT ventilador_CPU (Marca* | Modelo*)>
<!ELEMENT Nom (#PCDATA | Precio | Desc)*>
<!ELEMENT Precio (#PCDATA)>
<!ELEMENT Desc (#PCDATA)>
<!ELEMENT Clientes (Cliente)>
<!ELEMENT Cliente (ClienteID, Fecha_Alta, DNI_cliente, TipoCliente, Contacto, Direccion_completa, Datos_bancario)>
<!ELEMENT ClienteID (#PCDATA)>
<!ELEMENT Fecha_Alta (#PCDATA)>
<!ELEMENT DNI_cliente (DNI, Nombre_completo*, Domicilio, Info_nacimiento)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT Nombre_completo (nombre, apellido)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT Domicilio (Calle, Ciudad)>
<!ELEMENT Calle (#PCDATA)>
<!ELEMENT Ciudad (#PCDATA)>
<!ELEMENT Info_nacimiento (Fecha_nacimiento, Lugar_nacimiento)>
<!ELEMENT Fecha_nacimiento (#PCDATA)>
<!ELEMENT Lugar_nacimiento (#PCDATA)>
<!ELEMENT TipoCliente (Tipo, Tipo2)>
<!ELEMENT Tipo (#PCDATA)>
<!ELEMENT Tipo2 (#PCDATA)>
<!ELEMENT Contacto (Telefono, Email)>
<!ELEMENT Telefono (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Direccion_completa ANY>
<!ELEMENT Pais (#PCDATA)>
<!ELEMENT Dir_ciudad (#PCDATA)>
<!ELEMENT Municipio (#PCDATA |CodigoPostal)*>
<!ELEMENT CodigoPostal (#PCDATA)>
<!ELEMENT Direccion (callecasa, Piso, Puerta)>
<!ELEMENT callecasa (#PCDATA)>
<!ELEMENT Piso (#PCDATA)>
<!ELEMENT Puerta (#PCDATA)>
<!ELEMENT Region (#PCDATA)>
<!ELEMENT Datos_bancario (Numero_cuenta, cod, banco)>
<!ELEMENT Numero_cuenta (#PCDATA)>
<!ELEMENT cod (#PCDATA)>
<!ELEMENT banco (#PCDATA)>
<!ELEMENT Ordenes (Orden_Cliente)>
<!ELEMENT Orden_Cliente (clienteID, Nombre_completo, Fecha_Paquete, Envio_Info)>
<!ELEMENT clienteID (#PCDATA)>
<!ELEMENT Fecha_Paquete (Fecha_Orden, Fecha_Requerida)>
<!ELEMENT Fecha_Orden (#PCDATA)>
<!ELEMENT Fecha_Requerida (#PCDATA)>
<!ELEMENT Envio_Info (Envio_Via, Cargamento, Envio_embarcacion, Envio_Direccion, Envio_Ciudad, Envio_Region?, Envio_Codigo_Postal, Envio_Pais)>
<!ELEMENT Envio_Via (#PCDATA)>
<!ELEMENT Cargamento (#PCDATA)>
<!ELEMENT Envio_embarcacion (#PCDATA)>
<!ELEMENT Envio_Direccion (#PCDATA)>
<!ELEMENT Envio_Ciudad (#PCDATA)>
<!ELEMENT Envio_Region (#PCDATA)>
<!ELEMENT Envio_Codigo_Postal (#PCDATA)>
<!ELEMENT Envio_Pais (#PCDATA)>
<!ATTLIST Cliente numero_cliente ID #REQUIRED>
<!ATTLIST Envio_Info Envio_Fecha (2023-05-09T00:00:00) #REQUIRED>
<!ATTLIST Marca Nombre (MSI | ASUS | Keystone | Be_Quite) #REQUIRED>

<!-- 
CANVIS APLICATS RESPECT L'XML original
    
1. per fer que Marca sigui opcional, hem hagut d'utilitzar el pipe per definir els parents de Marca dintre de la definició del grandparents dels parents

2. linia 50 hem afegit el parent child de "Modelo" per no haver de fer més d'un pipe ja que "Nom" només surt una vegada. 

3. L'etiqueta Modelo a vegades conté text i quan definim com PCDATA, no pot contenir etiquetes. Si hi ha una forma de definir un element com PCDATA que pot o no tenir etiquetes, ho desconeixem
pel momennt. Per tant hem afegit Modelo com child obligatori de Modelo, ja que a l'XML base Modelo és una etiqueta opcional i a vegades 
s'utilitzava directament l'etiqueta Nom, que podia funcionar alhora com child de Marca o de Modelo. 

4. Per definir elements que poden contenir text i etiquetes (childs) la sintaxi és '(#PCDATA | childElement)*' El '*' permet que en cas de que no hi hagi text, encara pugui tener child. 

5. Algunes etiquetes com 'Precio' tenien majúscules inicials i altres no. Les hem estandaritzat amb majúscula inicial. XML és case sensitive, per tant és important que les etiquetes i atributs
s'escriguin igual tant a l'apertura com al tancament i a la resta d'instàncies en el document. 

6. Hem hagut de cambiar el nom de l'atribut "Be Quite" a "Be_quite" ja que DTD no admet espais com a nom. 

7. Hem eliminat els accents en algunes etiquets per evitar errors d'ambigüitat

8. Linia 185. Hem canviat el valor de '1' a 'a1' perquè sigui compatible segons la sintaxi de DTD

COSES APRESES DELS ERRORS
1. 
'<!ELEMENT Componentes (Placa_Base, Disco_duro, procesador, ram, refrigeración_liquida, torres, tarjeta_grafica, tarjeta_de_sonido, ventilador_CPU)>'
Havíem escrit aquesta línia i posava que Componentes havien de contenir els elements de dintre. Estaven tots subratllats en vermell excep Placa_Base.

L'error era que no havíem definit la resta de childs ja que pensava que al declarar-ho com child ja estava definit
Per tant hem hagut de copiar l'estructura de la definicio de l'element Placa_Base '<!ELEMENT Placa_Base (Marca* | Modelo*)>'i canviar el nom per cada child
i d'aquesta manera han desaparegut tots els errors. 

PROBLEMES 
1. <!ELEMENT Direccion_completa (Pais, Dir_ciudad, Municipio, Direccion, Region)>
dona error i tot està ben indentat i escrit, per això s'ha definit com ANY

-->

=== PabloJGA97/Pr-ctica-6-Validadors-d-XML-DTD/Practica 6. Exercici 7 i 8 XML DTD/grupalie.xml
<?xml version="1.0" encoding="UTF-8"?> <!--Para codificar y poder usar simbolos especiales-->
<!DOCTYPE TecnoComponentes SYSTEM "grupalie.dtd">
<TecnoComponentes> <!--Nombre de empresa-->
    <Componentes> <!--Seccion de componentes-->
        <Placa_Base> <!--Tipos de componentes que  tenemos-->
            <Marca Nombre="MSI"> <!--La marca o el proviedor de placabase-->
                <Modelo> <!--Modelos de placa base de marca "MSI" que esta en nuestro stock-->
                    <Nom>MSI Z790 GAMING PLUS WIFI 
                        <Precio>241€</Precio>
                    </Nom>
                    <Nom>MSI MEG Z790 ACE 
                        <Precio>759€</Precio>
                    </Nom>
                    <Nom> MSI MEG Z790 ACE MAX 
                        <Precio>759€</Precio>
                    </Nom>
                </Modelo>
            </Marca>
            <Marca Nombre="ASUS"> <!--La marca o el proviedor de placabase-->
                <Modelo> <!--Modelos de placa base de marca "Asus" que esta en nuestro stock-->
                    <Nom> ASUS ROG STRIX B550M-PLUS 
                        <Precio>369€</Precio>
                    </Nom>
                    <Nom> Asus ROG MAXIMUS Z690 EXTREME 
                        <Precio>1365€</Precio>
                    </Nom>
                    <Nom> ASUS ROG Maximus Z690 Hero EVA Edition 
                        <Precio>875€</Precio>
                    </Nom>
                </Modelo>
            </Marca>
        </Placa_Base>

        <Disco_duro> <!--Componentes Discos duro-->
            <Marca Nombre="Keystone">
                <Modelo>
                    <Nom>Kingston NV2 1TB SSD PCIe 4.0 NVMe Gen 4x4 
                        <Precio>54€</Precio>
                    </Nom>
                    <Nom>Kingston NV2 2TB SSD PCIe 4.0 NVMe Gen 4x4 
                        <Precio>103€</Precio>
                    </Nom>
                    <Nom> Kingston KC3000 SSD 2TB M.2 PCIe 4.0 NVMe 
                        <Precio>126€</Precio>
                    </Nom>
                </Modelo>
            </Marca>
        </Disco_duro>

        <procesador> <!--Componentes Procesador-->
            <Modelo>
                <Nom>Intel® Core™ i5
                    <Desc> 6 núcleos y 12 hilos</Desc>
                    <Precio>179,99€</Precio>
                </Nom>
                
                <Nom>AMD Ryzen 7 5800X
                    <Desc>16 núcleos,32 hilos</Desc>
                    <Precio>336,06€</Precio>
                </Nom>
                
                <Nom>Intel® Core™ i7-13700K
                    <Desc>16 núcleos,24 hilos</Desc>
                    <Precio>418,95€</Precio>
                </Nom>
            </Modelo> 
        </procesador>

        <ram><!--Componentes RAM-->
            <Modelo>
                <Nom> FURY Beast DDR4
                    <Desc>3200 MHz 16GB 2x8GB CL1</Desc>
                    <Precio>42,99€</Precio>
                </Nom>
            </Modelo>
            <Modelo>
                <Nom>Corsair Vengeance DDR5
                    <Desc>6000 MHz 2x16GB CL36</Desc>
                    <Precio>134€</Precio>
                </Nom>
            </Modelo>
            
            <Modelo>
                <Nom>Corsair Vengeance DDR5
                    <Desc>6000MHz 64GB 2x32GB CL30</Desc>
                    <Precio>306,79€</Precio>
                </Nom>
            </Modelo>
        </ram>

        <refrigeracion_liquida> <!--Componentes refigeración líquida -->
            <Marca Nombre="MSI">
                <Modelo>
                    <Nom>MSI MAG CORELIQUID E240 Kit de Refrigeración Líquida 
                        <Precio>132€</Precio>
                    </Nom>
                    <Nom>MSI MAG CORELIQUID P360 Kit de Refrigeración Líquida
                        <Precio>128€</Precio>
                    </Nom>
                    <Nom>MSI MAG CORELIQUID E360 Kit de Refrigeración Líquida
                        <Precio>160€</Precio>
                    </Nom>
                </Modelo>
            </Marca>
        </refrigeracion_liquida>

        <torres> <!--Componentes Torres -->
            <Marca Nombre = "ASUS">
                <Modelo>
                    <Nom>ASUS TUF Gaming GT502 Cristal Templado USB 3.0 Negra
                        <Precio>160€</Precio>
                    </Nom>
                    <Nom>
                        ASUS GX601 ROG Strix Helios Cristal Templado USB 3.0
                        <Precio>330€</Precio>
                    </Nom>
                    <Nom>ASUS ROG Hyperion GR701 Cristal Templado USB-C ARGB Negra
                        <Precio>430€</Precio>
                    </Nom>
                </Modelo>
            </Marca>
        </torres>

        <tarjeta_grafica> <!--Componentes Tarjeta Grafica-->
            <Modelo>
                <Nom>Gigabyte GeForce GT 710
                    <Desc>4096 x 2160 px 954 MHz</Desc>
                    <Precio>6045€</Precio>
                </Nom>
            </Modelo>
            
            <Modelo>
                <Nom>Gigabyte GeForce GT 1030
                    <Desc>1920 x 1200 px 1256 MHz</Desc>
                    <Precio>120,74€</Precio>
                </Nom>
            </Modelo>
           
            <Modelo>
                <Nom>GeForce RTX 4080
                    <Desc>7680 x 4320 px 2700 MHz</Desc>
                    <Precio>1529,00€</Precio>
                </Nom>
            </Modelo>
        </tarjeta_grafica>

        <tarjeta_de_sonido> <!--Componentes Tarjeta de sonido-->
            <Modelo>
                <Nom>Creative Sound Blaster Audigy
                    <Desc>120 dB,sonido 24 de bits y 192 kH</Desc>
                    <Precio>42,99€</Precio>
                </Nom>
            </Modelo>
            
            <Modelo>
                <Nom>Sound BlasterX AE-5 Plus
                    <Desc>122 db,sonido 32-bit y 384 kHz</Desc>
                    <Precio>111,99€</Precio>
                </Nom>
            </Modelo>
            
            <Modelo>
                <Nom>Creative Sound BlasterX AE-5
                    <Desc>122 dB,32-bit / 384 kHz</Desc>
                    <Precio>132,98€</Precio>
                </Nom>
            </Modelo>
        </tarjeta_de_sonido>

        <ventilador_CPU> <!--Componentes ventilador-->
            <Marca Nombre = "Be_Quite">
                <Modelo>
                    <Nom>Be Quiet Dark Rock Pro 4
                        <Precio>105€</Precio>
                    </Nom>
                    <Nom>Be Quiet Pure Rock 2 FX ARGB Ventilador CPU 120mm Negro
                        <Precio>60€</Precio>
                    </Nom>
                </Modelo>
            </Marca>
        </ventilador_CPU>
    </Componentes>
    
   <Clientes>
        <Cliente numero_cliente="a1"> <!--Numero de clientes-->
            <ClienteID>108</ClienteID> <!--ID del cliente en la página-->
            <Fecha_Alta>04/12/2023</Fecha_Alta> <!--Fecha de alta como comprador-->
            <DNI_cliente><!--Informacion del Cliente-->
                <DNI>499512203A</DNI>
                <Nombre_completo>
                    <nombre>Carla</nombre>
                    <apellido>Cuellar</apellido>
                </Nombre_completo>
                <Domicilio>
                    <Calle>Av. Carrilet 239</Calle>
                    <Ciudad>Barcelona</Ciudad>
                </Domicilio>
                <Info_nacimiento>
                    <Fecha_nacimiento>06-03-2002</Fecha_nacimiento>
                    <Lugar_nacimiento></Lugar_nacimiento>
                </Info_nacimiento>
            </DNI_cliente>
            <TipoCliente><!--Tipo de cliente si es empresa o particular-->
                <Tipo>Particular</Tipo>
                <Tipo2>Socio</Tipo2><!--Si es socio o no-->
            </TipoCliente>
            <Contacto><!--Informacion para contactar con el cliente-->
                <Telefono>679 569 45</Telefono>
                <Email>carla.cuellar@gmail.com</Email>
            </Contacto>
            <Direccion_completa> <!--Direccion del cliente actual-->
                <Pais>España</Pais>
                <Dir_ciudad>Barcelona</Dir_ciudad>
                <Municipio>L'hospitalet</Municipio>
                    <CodigoPostal>9740</CodigoPostal>
                <Direccion>
                    <callecasa>Calle Barcelona</callecasa>
                    <Piso>4-2</Piso>
                    <Puerta>2</Puerta>
                </Direccion>
                <Region>0</Region>
            </Direccion_completa>
            <Datos_bancario><!--Datos del banco del cliente-->
                <Numero_cuenta>ES2123342343242</Numero_cuenta>
                <cod>804</cod>
                <banco>Caixa Bank</banco>
            </Datos_bancario>
        </Cliente>
    </Clientes>

    <Ordenes>
        <Orden_Cliente>
            <clienteID>108</clienteID>
            <Nombre_completo>
                <nombre>Carla</nombre>
                <apellido>Cuellar</apellido>
            </Nombre_completo>
            <Fecha_Paquete>
                <Fecha_Orden>2023-05-06T00:00:00</Fecha_Orden>
                <Fecha_Requerida>2023-05-20T00:00:00</Fecha_Requerida>
            </Fecha_Paquete>
            <Envio_Info Envio_Fecha="2023-05-09T00:00:00">
                <Envio_Via>2</Envio_Via>
                <Cargamento>3.35</Cargamento>
                <Envio_enbarcancion>Iberia</Envio_enbarcancion>
                <Envio_Direccion>Calle Iberia 234</Envio_Direccion>
                <Envio_Ciudad>Madrid</Envio_Ciudad>
                <Envio_REgion>O</Envio_REgion>
                <Envio_Codigo_Postal>97403</Envio_Codigo_Postal>
